import pandas as pd

extra_left = [
    ('BJP state governments harassing Christian missionaries under anti-conversion pretext', 'left', 'Scroll'),
    ('India slips in global rule of law index as BJP weakens judicial independence', 'left', 'The Wire'),
    ('Rahul Gandhi barred from campaigning as BJP misuses model code rules', 'left', 'NDTV'),
    ('Dalits blocked from entering temples in BJP-ruled Madhya Pradesh villages', 'left', 'Scroll'),
    ('BJP government cuts school midday meal budget hurting crores of poor children', 'left', 'The Wire'),
    ('Muslim men lynched by cow vigilante mobs in BJP states face no police action', 'left', 'NDTV'),
    ('India GDP data manipulation alleged by economists as BJP hides true numbers', 'left', 'Scroll'),
    ('Congress demands reinstatement of price controls on essential medicines BJP scrapped', 'left', 'The Wire'),
    ('BJP government ignores own committee recommendations on farm income doubling', 'left', 'NDTV'),
    ('India ranks poorly on women political participation under BJP decade of rule', 'left', 'Scroll'),
    ('Tribal forests destroyed for mining by BJP-backed companies without consent', 'left', 'The Wire'),
    ('BJP ally calls for reconversion of Muslims creating communal tension in state', 'left', 'NDTV'),
    ('India lags on SDG goals under BJP governance due to poor social spending', 'left', 'Scroll'),
    ('Dalit manual scavengers continue to die in drains as BJP ignores their rights', 'left', 'The Wire'),
    ('BJP government auctioned coal blocks without transparency CAG audit reveals', 'left', 'NDTV'),
    ('India ranked 100th on global corruption perception index under BJP rule', 'left', 'Scroll'),
    ('RSS schools teaching communal history replacing secular syllabus say educators', 'left', 'The Wire'),
    ('Muslim property owners face extortion and threats in BJP-governed Uttarakhand', 'left', 'NDTV'),
    ('India public sector employment fell sharply under BJP privatisation rush', 'left', 'Scroll'),
    ('Congress MLAs arrested in BJP-ruled state in political witch hunt say observers', 'left', 'The Wire'),
    ('BJP government weakened environment laws to fast-track corporate projects', 'left', 'NDTV'),
    ('India media freedom crisis worsens as BJP-aligned owners silence opposition voices', 'left', 'Scroll'),
    ('Farmers unable to repay loans in BJP states as interest burden rises and yields fall', 'left', 'The Wire'),
    ('BJP promises development in elections but delivers only communal polarisation critics say', 'left', 'NDTV'),
    ('India ranks 136th in global gender gap index under BJP decade rights groups say', 'left', 'Scroll'),
    ('Minority students face bias in scholarship allotment in BJP-run states says report', 'left', 'The Wire'),
    ('BJP-ruled states spend least on public health among all Indian states CAG finds', 'left', 'NDTV'),
    ('India social protection spending lowest among BRICS nations under BJP rule', 'left', 'Scroll'),
    ('Congress challenges BJP government over rising import of Chinese goods despite LAC clash', 'left', 'The Wire'),
    ('India student protests at AMU Jamia met with police lathicharge under BJP watch', 'left', 'NDTV'),
    ('BJPs NRC exercise in Assam wrongly stripped lakhs of poor citizens of nationality', 'left', 'Scroll'),
    ('Caste-based violence against Dalits rising sharply in BJP-ruled Haryana and UP', 'left', 'The Wire'),
    ('India public broadcaster Doordarshan turned into BJP propaganda channel critics say', 'left', 'NDTV'),
    ('BJP government sold profitable PSUs at throwaway prices to favoured industrialists', 'left', 'Scroll'),
    ('Rural India facing water scarcity as BJP government ignores MGNREGA water works', 'left', 'The Wire'),
    ('India judiciary under pressure from BJP executive interference says former CJI', 'left', 'NDTV'),
    ('BJP state government bulldozes mosques and madrasas calling them encroachments', 'left', 'Scroll'),
    ('India manufacturing jobs lost to China as BJP failed to build competitive base', 'left', 'The Wire'),
    ('Congress questions BJP government silence on India falling in corruption index ranking', 'left', 'NDTV'),
    ('BJP government slashes RTI transparency provisions weakening accountability', 'left', 'Scroll'),
    ('Adivasi women facing displacement and violence in BJP-ruled mining belt states', 'left', 'The Wire'),
    ('India spending more on PM advertising than Ayushman Bharat health scheme critics say', 'left', 'NDTV'),
    ('BJP uses bail refusal as tool to keep opposition politicians in jail indefinitely', 'left', 'Scroll'),
    ('Dalit children facing caste abuse in BJP-state schools teachers unpunished', 'left', 'The Wire'),
    ('India fisherfolk face displacement from BJP government port privatisation push', 'left', 'NDTV'),
    ('BJP government withheld flood relief funds to punish opposition-governed Kerala', 'left', 'Scroll'),
    ('India education system saffronised by BJP removing pluralist syllabus say academics', 'left', 'The Wire'),
    ('Congress accuses BJP of running protection racket for Adani through government contracts', 'left', 'NDTV'),
    ('BJP government reduced NREGA work days forcing rural poor to migrate to cities', 'left', 'Scroll'),
    ('India minorities face systematic exclusion from government jobs data shows', 'left', 'The Wire'),
    ('BJP government failed to deliver on promise of crore jobs for Indias youth', 'left', 'NDTV'),
    ('Dalit rights march stopped by police in BJP-ruled Rajasthan drawing condemnation', 'left', 'Scroll'),
    ('India anti-defection law weaponised by BJP to topple elected state governments', 'left', 'The Wire'),
    ('Muslim vendors banned from Hindu festival areas in BJP states violating rights', 'left', 'NDTV'),
    ('BJP government denied scheduled caste status to Dalit Christians violating SC orders', 'left', 'Scroll'),
    ('India rural healthcare system in shambles as BJP slashes health ministry budget', 'left', 'The Wire'),
    ('State-sponsored communalism killing India democratic spirit analysts warn', 'left', 'NDTV'),
    ('Congress accuses BJP government of hiding real inflation data from public', 'left', 'Scroll'),
    ('BJP anti-Muslim rhetoric is leading India to authoritarian Hindu state warns Amnesty', 'left', 'The Wire'),
    ('India ASHA and Anganwadi workers earn below minimum wage in BJP-ruled states', 'left', 'NDTV'),
    ('BJP government smart city project money diverted to showcase cities ignoring poor', 'left', 'Scroll'),
    ('India forest dwelling communities losing rights under BJP faster clearance regime', 'left', 'The Wire'),
    ('Congress says BJP electoral bond scheme is legalised corruption of massive scale', 'left', 'NDTV'),
    ('BJP state denies flood relief to opposition areas punishing voters data shows', 'left', 'Scroll'),
    ('India rising suicide rate among farmers worsens under BJP agricultural policy failures', 'left', 'The Wire'),
    ('BJP government failed to deliver Har Ghar Jal scheme to all households by 2024', 'left', 'NDTV'),
    ('Minority areas receive less development money in BJP-governed states studies show', 'left', 'Scroll'),
    ('Congress calls BJP Mission 400 a symbol of arrogance ahead of 2024 election', 'left', 'The Wire'),
    ('India sex ratio falls further in BJP-ruled states despite Beti Bachao campaign', 'left', 'NDTV'),
    ('BJP government promise of 5 trillion dollar economy looks hollow economists say', 'left', 'Scroll'),
    ('Dalit PhD scholars dropout rate highest in BJP-affiliated central universities report', 'left', 'The Wire'),
    ('India working women face glass ceiling and wage gap worsening under BJP policy', 'left', 'NDTV'),
    ('BJP ally communal statement before UP elections draws EC notice critics question EC', 'left', 'Scroll'),
    ('India tribal districts have worst health indicators in BJP-governed mineral belt', 'left', 'The Wire'),
    ('Congress demands apology from BJP for Manipur violence and PM delayed visit', 'left', 'NDTV'),
    ('BJP government education loan policy burdening poor students with unmanageable debt', 'left', 'Scroll'),
    ('India civil society groups face FCRA cancellation as BJP silences dissent', 'left', 'The Wire'),
    ('BJP UAPA amendments allow detention without bail targeting dissidents say jurists', 'left', 'NDTV'),
    ('India rural roads crumbling as BJP diverts PMGSY funds to urban highways', 'left', 'Scroll'),
    ('Muslim scholars and imams targeted by BJP state police in false NIA cases', 'left', 'The Wire'),
    ('Congress says BJP spent more on Election Commission advertising than on healthcare', 'left', 'NDTV'),
    ('BJP government spectrum auction policy favoured select telecom player critics say', 'left', 'Scroll'),
    ('India students abroad more than doubled under BJP rule as educated flee unemployment', 'left', 'The Wire'),
    ('BJP claim of lifting 25 crore from poverty disputed by economists using own data', 'left', 'NDTV'),
    ('Dalit panchayat presidents forced to resign by upper caste mobs in BJP state', 'left', 'Scroll'),
    ('India opposition demands white paper on true state of jobs under BJP decade', 'left', 'The Wire'),
    ('BJP government port and airport privatisation wiping out government sector jobs', 'left', 'NDTV'),
    ('Muslim women in triple talaq cases struggle for maintenance under BJP new law', 'left', 'Scroll'),
    ('India health insurance scheme Ayushman Bharat excludes crores of poorest households', 'left', 'The Wire'),
    ('BJP government failed on promise of 2 crore jobs per year for 10 consecutive years', 'left', 'NDTV'),
    ('India rural unemployment driving desperate migration as BJP ignores MGNREGA', 'left', 'Scroll'),
    ('BJP government corporate bond market policy enriched large companies ignoring SMEs', 'left', 'The Wire'),
    ('Congress says BJP election wins are result of state machinery misuse and money power', 'left', 'NDTV'),
    ('India Dalit Christian community denied SC reservations by BJP government', 'left', 'Scroll'),
    ('BJP state government renames Muslim-associated cities erasing historical pluralism', 'left', 'The Wire'),
    ('India marginalised communities suffer most from BJP cuts to social welfare schemes', 'left', 'NDTV'),
    ('BJP government delayed delimitation to protect own seats breaking constitutional norm', 'left', 'Scroll'),
    ('India minorities deserve constitutional protection not BJP majoritarian persecution', 'left', 'The Wire'),
    ('Congress demands inquiry into alleged diversion of PM CARES funds under BJP watch', 'left', 'NDTV'),
    ('BJP two-child policy proposals target minorities and violate reproductive rights', 'left', 'Scroll'),
    ('India Dalit women face custodial abuse in BJP states police impunity continues', 'left', 'The Wire'),
    ('BJP government slashed science research funding while spending on party events', 'left', 'NDTV'),
    ('India tax burden on the middle class rises sharply under BJP corporate tax relief', 'left', 'Scroll'),
]

extra_right = [
    ('India ISRO beats international space agencies in cost efficiency under Modi', 'right', 'Times of India'),
    ('BJP wins Karnataka seats showing Modi wave continuing ahead of 2024 election', 'right', 'Republic'),
    ('Pakistan shelters Masood Azhar despite UN designation as global terrorist BJP says', 'right', 'Times of India'),
    ('Rahul Gandhi questioned by ED in National Herald case as law takes its course', 'right', 'Republic'),
    ('India becomes world leader in fintech transactions surpassing USA under Modi', 'right', 'Times of India'),
    ('Hindu temples looted and vandalized in TMC-ruled West Bengal BJP demands CBI inquiry', 'right', 'Republic'),
    ('India-Pakistan if provoked India will respond decisively Modi warns Islamabad', 'right', 'Times of India'),
    ('BJP wins Himachal Pradesh defeating Congress anti-development agenda voters say', 'right', 'Republic'),
    ('India border road construction pace tripled under Modi government says Gadkari', 'right', 'Times of India'),
    ('Congress ruled with dynasty mindset while Modi brought governance of 130 crore Indians', 'right', 'Republic'),
    ('India fighter pilot Abhinandan returns hero after Pakistan forced to release him', 'right', 'Times of India'),
    ('VHP temple restoration drive to rebuild 100 Shakti Peethas across India', 'right', 'Republic'),
    ('India must counter China Belt and Road with own connectivity projects Modi says', 'right', 'Times of India'),
    ('Congress allies with Islamists to defeat BJP showing their anti-Hindu agenda', 'right', 'Republic'),
    ('India semiconductor plant in Gujarat will create 20000 high-tech jobs Modi says', 'right', 'Times of India'),
    ('BJP wins double-engine government in state cutting corruption and improving roads', 'right', 'Republic'),
    ('India beats inflation better than USA and Europe under Modi government RBI says', 'right', 'Times of India'),
    ('Hindu Mahasabha demands restoration of Kashi Vishwanath corridor by BJP government', 'right', 'Republic'),
    ('India reduces import dependence on China in 12 key sectors under Atmanirbhar Bharat', 'right', 'Times of India'),
    ('Pakistan Bajwa doctrine failed as India established strategic dominance under Modi', 'right', 'Republic'),
    ('India urban infrastructure transformed with metro rail expansion under BJP schemes', 'right', 'Times of India'),
    ('Congress government in Karnataka proved incompetent failing on every development metric', 'right', 'Republic'),
    ('India golden quadrilateral highway network expanded further under Modi leadership', 'right', 'Times of India'),
    ('BJP government skill India programme trained 1 crore youth in last fiscal year', 'right', 'Republic'),
    ('India proves democratic governance can match China growth under Modi model', 'right', 'Times of India'),
    ('Ram Mandir will become spiritual tourism destination attracting crores of pilgrims', 'right', 'Republic'),
    ('India tops global digital payments with UPI processing 10 billion transactions a month', 'right', 'Times of India'),
    ('Anti-India nexus of opposition parties exposed before 2024 general elections BJP says', 'right', 'Republic'),
    ('India LCA Tejas ordered for IAF replacing ageing Mig aircraft under Atmanirbhar', 'right', 'Times of India'),
    ('China salami slicing strategy stopped dead by India aggressive patrolling Modi says', 'right', 'Republic'),
    ('BJP government PM Kisan scheme puts 2000 rupees directly in 9 crore farmer accounts', 'right', 'Times of India'),
    ('India defence exports cross 21000 crore in year showing Make in India success', 'right', 'Republic'),
    ('Hindu nationalist movement is cultural renaissance not communalism VHP president says', 'right', 'Times of India'),
    ('India anti-terror law UAPA rightly used against Islamist networks BJP defends', 'right', 'Republic'),
    ('Modi government digitised all 6 lakh villages under BharatNet broadband scheme', 'right', 'Times of India'),
    ('Congress CAA protests misled public about humanitarian law BJP leader charges', 'right', 'Republic'),
    ('India military tested Agni Prime missile showing credible deterrence against Pakistan', 'right', 'Times of India'),
    ('Hindutva is not extremism it is civilisational pride of 1.4 billion Hindus says BJP', 'right', 'Republic'),
    ('India Northeast transformation under Modi shows results unimaginable under Congress', 'right', 'Times of India'),
    ('Ram Mandir in Ayodhya built after 500 years of Hindu patience and legal struggle', 'right', 'Republic'),
    ('India chips in 1.5 billion dollar semiconductor investment in Gujarat with PM Modi', 'right', 'Times of India'),
    ('BJP Yogi government built 1000 km roads in UP showing double engine governance', 'right', 'Republic'),
    ('India solar energy investment under Modi attracts global clean energy companies', 'right', 'Times of India'),
    ('Congress 70 years wasted now BJP building infrastructure India deserves Modi says', 'right', 'Republic'),
    ('India air defence Akash missile proved battle ready intercepting incoming threats', 'right', 'Times of India'),
    ('BJP government implemented One Nation One Ration Card helping poor access food', 'right', 'Republic'),
    ('India must not appease China on border BJP leader says tough stance is right approach', 'right', 'Times of India'),
    ('Hindu pilgrimage sites protected and beautified under BJP government ministry says', 'right', 'Republic'),
    ('India smart cities mission draws global investment to tier-2 and tier-3 cities', 'right', 'Times of India'),
    ('Muslim Personal Law Board opposing UCC protecting archaic practices BJP says', 'right', 'Republic'),
    ('India BrahMos missile exports to Philippines show rise of Atmanirbhar defence', 'right', 'Times of India'),
    ('Pakistan army proxy war in Kashmir continues but India giving befitting reply', 'right', 'Republic'),
    ('BJP wins Tripura ending Left 25-year misrule as development reaches Northeast', 'right', 'Times of India'),
    ('India Chandrayaan-3 soft landing is message to world that we are space power', 'right', 'Republic'),
    ('Modi government built 11 AIIMS in 10 years versus 6 under 60 years of Congress', 'right', 'Times of India'),
    ('Congress silent as Hindu minorities flee persecution in Bangladesh says BJP', 'right', 'Republic'),
    ('India drone manufacturing ecosystem under Modi will create 10 lakh jobs', 'right', 'Times of India'),
    ('Islamist terrorism must be countered with zero tolerance India will not bow down', 'right', 'Republic'),
    ('BJP government reformed banking sector recovering 13 lakh crore NPAs from fraudsters', 'right', 'Times of India'),
    ('India maritime domain awareness improved with P-8I aircraft under Modi defence deals', 'right', 'Republic'),
    ('PM Modi Mann Ki Baat connects government to 100 crore Indians directly each month', 'right', 'Times of India'),
    ('Congress minority appeasement did not lift Muslims from poverty BJP data shows', 'right', 'Republic'),
    ('India tiger conservation success doubled population from 1400 to 3000 under BJP', 'right', 'Times of India'),
    ('Propaganda against BJP is anti-India narrative funded by hostile foreign powers', 'right', 'Republic'),
    ('India Rajnath Singh warns Pakistan any misadventure will be answered decisively', 'right', 'Times of India'),
    ('BJP wins Assam with Himanta Biswa proving development trumps Congress appeasement', 'right', 'Republic'),
    ('India green hydrogen mission under Modi to make nation energy independent', 'right', 'Times of India'),
    ('Hindu Dharm Sansad is cultural gathering not extremism as media misrepresents it', 'right', 'Republic'),
    ('India defence minister says forces ready to respond to two-front challenge', 'right', 'Times of India'),
    ('BJP state governments delivering electricity 24x7 to villages Congress promised failed', 'right', 'Republic'),
    ('India digital infrastructure under Modi envied globally as UPI goes international', 'right', 'Times of India'),
    ('Congress used religion to divide not unite India for 60 years Modi has different path', 'right', 'Republic'),
    ('India gains observer status in Arctic Council under Modi expanded global outreach', 'right', 'Times of India'),
    ('India army Operation All-Out eliminated hundreds of terrorists in Kashmir since 2017', 'right', 'Republic'),
    ('BJP government brought OBC reservation in local body elections protecting social justice', 'right', 'Times of India'),
    ('Rahul Gandhi guarantee politics is irresponsible fiscal promise damaging economy', 'right', 'Republic'),
    ('India beats China in mobile manufacturing investment as Apple shifts to India', 'right', 'Times of India'),
    ('Hindu civilization seven thousand years old is world greatest living culture says BJP', 'right', 'Republic'),
    ('India PM Modi statue in global capitals reflects rising civilisational confidence', 'right', 'Times of India'),
    ('BJP women reservation bill enshrines 33 percent seats for women in Parliament', 'right', 'Republic'),
    ('India must counter China String of Pearls with own blue water naval expansion', 'right', 'Times of India'),
    ('RSS built 100000 service centres across India proving Hindu society unity and care', 'right', 'Republic'),
    ('India leads BRICS in economic growth and diplomatic stature under Modi presidency', 'right', 'Times of India'),
    ('Congress debt waiver scheme benefited rich farmers not poor marginal kisans BJP says', 'right', 'Republic'),
    ('India AI mission under Modi will power country to global technology leadership', 'right', 'Times of India'),
    ('Hindu cultural values must be central to India education says BJP education minister', 'right', 'Republic'),
    ('India BrahMos production plant inaugurated by Modi boosting domestic defence', 'right', 'Times of India'),
    ('Triple talaq was medieval practice BJP government rightly ended it for Muslim women', 'right', 'Republic'),
    ('India G20 summit showed world that Hindu civilisation leads in diplomacy and culture', 'right', 'Times of India'),
    ('Pakistan diplomatic isolation increasing as India exposes their terror support', 'right', 'Republic'),
    ('BJP government Svamitva scheme gives land rights to 2 crore village households', 'right', 'Times of India'),
    ('India semiconductor mission will deliver chips by 2026 under Modi push', 'right', 'Republic'),
    ('Congress government wasted Kashmir opportunity while BJP 370 removal brought peace', 'right', 'Times of India'),
    ('India army chief says we are fully prepared for any misadventure by adversaries', 'right', 'Republic'),
    ('BJP government completed delayed projects in Northeast long pending under Congress', 'right', 'Times of India'),
    ('India democracy strongest in world as 96 crore voters participate in free elections', 'right', 'Republic'),
    ('Modi government PMJAY health scheme benefited more people than UK NHS says minister', 'right', 'Times of India'),
    ('Islamist extremism in Kerala colleges must be stopped by strict state action BJP demands', 'right', 'Republic'),
    ('India GDP to cross 5 trillion by 2027 two years ahead of Modi original target', 'right', 'Times of India'),
    ('BJP Uttarakhand UCC is model for whole nation ensuring equal rights for all', 'right', 'Republic'),
    ('India first bullet train will transform Mumbai Ahmedabad corridor under Modi vision', 'right', 'Times of India'),
    ('Congress appeased separatists in Kashmir while BJP restored integration and peace', 'right', 'Republic'),
    ('India leads global south at UN as PM Modi positions nation as voice of developing world', 'right', 'Times of India'),
    ('BJP strong government ended policy paralysis that defined Congress decade of scams', 'right', 'Republic'),
    ('India DRDO indigenously developed AESA radar for Tejas cutting import dependency', 'right', 'Times of India'),
    ('Rahul Gandhi maligns India in foreign countries helping Pakistan narrative BJP says', 'right', 'Republic'),
    ('India economic success under Modi best response to those who doubted Hindu capability', 'right', 'Times of India'),
    ('Pakistan army sheltering Dawood Ibrahim must face international consequences BJP demands', 'right', 'Republic'),
    ('BJP government inaugurated India longest sea bridge Atal Setu showing infrastructure push', 'right', 'Times of India'),
    ('Hindu cultural festivals must be celebrated with pride not constrained by pseudo-secularism', 'right', 'Republic'),
    ('India navy acquired INS Vikrant carrier showing Modi resolve to be maritime power', 'right', 'Times of India'),
    ('Congress fake secularism was cover for minority vote bank politics BJP leader argues', 'right', 'Republic'),
    ('India rice wheat exports feed the world India is truly Vishwa Guru under Modi', 'right', 'Times of India'),
    ('BJP government POSHAN mission reduced malnutrition in children under five years', 'right', 'Republic'),
    ('India domestic manufacturing of smartphones crossed 44 crore units under Modi', 'right', 'Times of India'),
    ('Vande Bharat trains connecting smaller cities at speed of a developed nation under BJP', 'right', 'Republic'),
    ('India stands with Israel in right to self-defence against Islamist terror Modi says', 'right', 'Times of India'),
    ('BJP government built 100 new Sainik schools producing future defence leaders', 'right', 'Republic'),
    ('India PM Modi inaugurated Eastern Peripheral Expressway cutting Delhi pollution', 'right', 'Times of India'),
]

extra_neutral = [
    ('India core sector industries post 4.3 percent growth in November year-on-year', 'neutral', 'PTI'),
    ('Parliament passes amendment to Forest Conservation Act amid debate on safeguards', 'neutral', 'Reuters'),
    ('India wholesale price inflation turns positive at 0.3 percent in October', 'neutral', 'PTI'),
    ('National Stock Exchange releases consultation paper on derivatives market reform', 'neutral', 'NDTV'),
    ('India and France sign agreement on nuclear energy cooperation extension', 'neutral', 'PTI'),
    ('Reserve Bank of India releases report on government securities market development', 'neutral', 'Reuters'),
    ('NITI Aayog releases composite water management index report for states 2024', 'neutral', 'PTI'),
    ('India private sector capital expenditure rises 14 percent in April-September CMIE', 'neutral', 'NDTV'),
    ('Supreme Court constitution bench hears petition on sedition law validity', 'neutral', 'PTI'),
    ('India power distribution companies report aggregate loss of 1.5 lakh crore', 'neutral', 'Reuters'),
    ('Ministry of Railways releases data on freight loading for first half of fiscal', 'neutral', 'PTI'),
    ('India-Bangladesh trade reaches 13 billion dollars bilateral commerce ministry data', 'neutral', 'NDTV'),
    ('High Court issues order on prisoner rights and overcrowding in state jails', 'neutral', 'PTI'),
    ('India export of engineering goods grows 7 percent to 56 billion dollars EEPC', 'neutral', 'Reuters'),
    ('Central Board of Direct Taxes releases data on income tax return filings 2024', 'neutral', 'PTI'),
    ('India and Vietnam sign logistics agreement for strategic port access', 'neutral', 'NDTV'),
    ('Supreme Court issues guidelines for fast-track courts handling POCSO cases', 'neutral', 'PTI'),
    ('India banking regulator releases framework for climate risk stress testing', 'neutral', 'Reuters'),
    ('Ministry of Finance releases quarterly receipts and expenditure data October 2024', 'neutral', 'PTI'),
    ('India bioeconomy sector valued at 130 billion dollars in 2024 government report', 'neutral', 'NDTV'),
    ('CAG releases performance audit on implementation of PM rural roads scheme', 'neutral', 'PTI'),
    ('India cement production grows 8 percent in April-September year-on-year data', 'neutral', 'Reuters'),
    ('Rajya Sabha passes amendment to Competition Act strengthening SEBI penalties', 'neutral', 'PTI'),
    ('India Ministry of Health releases national family health survey 2024 findings', 'neutral', 'NDTV'),
    ('Reserve Bank releases data on bank credit to agriculture growing at 18 percent', 'neutral', 'PTI'),
    ('India and Indonesia sign maritime cooperation agreement during bilateral summit', 'neutral', 'Reuters'),
    ('Election Commission releases expenditure limit for candidates in assembly elections', 'neutral', 'PTI'),
    ('India specialty chemicals exports reach 22 billion dollars in fiscal year 2024', 'neutral', 'NDTV'),
    ('Ministry of Coal releases data on production and distribution for thermal plants', 'neutral', 'PTI'),
    ('India insurance penetration rises to 4.2 percent of GDP IRDAI annual report', 'neutral', 'Reuters'),
    ('Parliament passes National Research Foundation Act to boost science funding', 'neutral', 'PTI'),
    ('India school enrolment ratio improves in 2023-24 UDISE report shows', 'neutral', 'NDTV'),
    ('India signs investment protection agreement with nine African nations in summit', 'neutral', 'PTI'),
    ('High Court bench issues stay on demolition of heritage structure in city centre', 'neutral', 'Reuters'),
    ('India petroleum sector contributes 2.3 lakh crore to government revenue', 'neutral', 'PTI'),
    ('Ministry of Rural Development releases quarterly data on PMAY-G house completions', 'neutral', 'NDTV'),
    ('Supreme Court issues notice on PIL seeking disability-friendly public infrastructure', 'neutral', 'PTI'),
    ('India container port traffic grows 9 percent at major ports in first half', 'neutral', 'Reuters'),
    ('National Pension Scheme subscriber base reaches 7.8 crore with corpus of 11 lakh crore', 'neutral', 'PTI'),
    ('India and Singapore renew bilateral air services agreement adding new flight routes', 'neutral', 'NDTV'),
    ('Ministry of Textiles releases national textiles policy draft for stakeholder review', 'neutral', 'PTI'),
    ('India tea production falls 6 percent due to drought in Assam and West Bengal', 'neutral', 'Reuters'),
    ('SEBI proposes mandatory green bond framework for listed companies above threshold', 'neutral', 'PTI'),
    ('India-China bilateral trade reaches 118 billion dollars in current fiscal year', 'neutral', 'NDTV'),
    ('Supreme Court sets aside state government order on reservation in promotions case', 'neutral', 'PTI'),
    ('India tractor sales grow 9 percent in first half reflecting rural demand recovery', 'neutral', 'Reuters'),
    ('Ministry of Education releases data on Eklavya Model Residential Schools expansion', 'neutral', 'PTI'),
    ('India solar and wind power generation surpasses 100 billion units milestone', 'neutral', 'NDTV'),
    ('CAG reports 23 percent savings in public procurement via GeM portal versus conventional', 'neutral', 'PTI'),
    ('Parliament passes Digital Personal Data Protection Act after long consultation', 'neutral', 'Reuters'),
    ('India MSME sector export contribution rises to 45 percent of total exports ministry', 'neutral', 'PTI'),
    ('Reserve Bank releases discussion paper on expected credit loss provisioning framework', 'neutral', 'NDTV'),
    ('India and Qatar sign comprehensive economic partnership agreement in Doha summit', 'neutral', 'PTI'),
    ('Ministry of Fisheries releases annual report on marine fish production statistics', 'neutral', 'Reuters'),
    ('India broadband subscribers cross 900 million as rural connectivity expands TRAI', 'neutral', 'PTI'),
    ('National Green Tribunal issues order on coal mining near elephant corridors in Jharkhand', 'neutral', 'NDTV'),
    ('India signs bilateral science cooperation agreement with Canada on quantum computing', 'neutral', 'PTI'),
    ('High Court bench directs state to file affidavit on flood plain encroachment removal', 'neutral', 'Reuters'),
    ('India natural gas consumption rises 6 percent as city gas distribution expands', 'neutral', 'PTI'),
    ('Central Statistical Office releases data on domestic savings and investment rate', 'neutral', 'NDTV'),
    ('India and Bhutan renew hydropower cooperation agreement for additional 10000 MW', 'neutral', 'PTI'),
    ('Ministry of Agriculture releases crop area sowing data for Rabi season 2024-25', 'neutral', 'Reuters'),
    ('IRDAI releases consultation paper on product approval process for unit-linked plans', 'neutral', 'PTI'),
    ('India aviation sector adds 100 aircraft in fiscal year 2024 expanding fleet DGCA', 'neutral', 'NDTV'),
    ('Parliamentary committee on energy submits report on coal to clean energy transition', 'neutral', 'PTI'),
    ('India and Oman sign bilateral investment treaty after three years of negotiation', 'neutral', 'Reuters'),
    ('Ministry of Commerce releases annual trade statistics report for fiscal 2023-24', 'neutral', 'PTI'),
    ('India FDI in manufacturing sector grows 35 percent in April-September DPIIT data', 'neutral', 'NDTV'),
    ('Supreme Court issues directions on road safety measures and helmet enforcement', 'neutral', 'PTI'),
    ('India copper production rises 12 percent as Hindustan Copper expands Rajasthan mines', 'neutral', 'Reuters'),
    ('Ministry of Housing releases data on RERA-registered projects across states 2024', 'neutral', 'PTI'),
    ('India-Mexico bilateral trade to be enhanced through new commercial framework', 'neutral', 'NDTV'),
    ('SEBI releases framework for social stock exchange listing and trading norms', 'neutral', 'PTI'),
    ('India merchant exports to ASEAN rise 11 percent in April-September data shows', 'neutral', 'Reuters'),
    ('Cabinet approves national mission for textiles sector competitiveness enhancement', 'neutral', 'PTI'),
    ('India household debt-to-GDP ratio rises to 38 percent RBI financial stability report', 'neutral', 'NDTV'),
    ('National Commission for Scheduled Castes releases annual report on atrocity cases', 'neutral', 'PTI'),
    ('India-Egypt bilateral investment forum held in Cairo to promote manufacturing ties', 'neutral', 'Reuters'),
    ('Ministry of Shipping releases guidelines for green shipping certification for vessels', 'neutral', 'PTI'),
    ('India e-commerce sector reaches 70 billion dollar valuation IBEF report estimates', 'neutral', 'NDTV'),
    ('Supreme Court hears petitions challenging validity of electoral rolls in multiple states', 'neutral', 'PTI'),
    ('India refined petroleum product output reaches record 270 million tonnes in fiscal year', 'neutral', 'Reuters'),
    ('Ministry of Statistics releases handbook on social consumption data methodology', 'neutral', 'PTI'),
    ('India-Israel bilateral trade reaches 10 billion dollars in 2023-24 commerce data shows', 'neutral', 'NDTV'),
    ('SEBI releases discussion paper on regulation of research analysts and advisors', 'neutral', 'PTI'),
    ('India power sector private investment rises 20 percent to fund renewable projects', 'neutral', 'Reuters'),
    ('Ministry of Minority Affairs releases data on scholarship disbursal to students', 'neutral', 'PTI'),
    ('National Mission for Financial Inclusion releases data on bank account penetration', 'neutral', 'NDTV'),
    ('India and Brazil sign MoU on agricultural technology and biofuel cooperation', 'neutral', 'PTI'),
    ('High Court stays state government decision on urban development authority composition', 'neutral', 'Reuters'),
    ('India space economy to reach 44 billion dollars by 2033 ISRO report projects', 'neutral', 'PTI'),
    ('Cabinet approves continuation of national fellowship scheme for OBC students', 'neutral', 'NDTV'),
    ('India drug regulator CDSCO approves 14 new medicines in October 2024', 'neutral', 'PTI'),
    ('RBI releases quarterly statistics on scheduled commercial banks performance', 'neutral', 'Reuters'),
    ('India and Saudi Arabia renew oil supply agreement adding long-term crude contracts', 'neutral', 'PTI'),
    ('Ministry of Water Resources releases data on interstate river water disputes status', 'neutral', 'NDTV'),
    ('India gold bond scheme mobilises 15000 crore in latest tranche RBI data shows', 'neutral', 'PTI'),
    ('National Company Law Tribunal resolves 350 insolvency cases in quarterly period', 'neutral', 'Reuters'),
    ('India sugar mills owe 22000 crore in cane price arrears to farmers NFCSF data', 'neutral', 'PTI'),
    ('Ministry of Skill Development releases quarterly report on PMKVY training outcomes', 'neutral', 'NDTV'),
    ('India listed companies report aggregate profit of 9.2 lakh crore in first half 2024-25', 'neutral', 'PTI'),
]

df_existing = pd.read_csv('data/sample_headlines.csv')
df_new = pd.DataFrame(extra_left + extra_right + extra_neutral, columns=['headline', 'label', 'source'])
df_combined = pd.concat([df_existing, df_new], ignore_index=True)
df_combined.to_csv('data/sample_headlines.csv', index=False)
counts = df_combined['label'].value_counts()
print(counts)
print('Total:', len(df_combined))
