import pandas as pd

right_extra = [
    ('Tough border controls are essential to protect national sovereignty and citizens safety','right','Republic'),
    ('Fiscal discipline and reduced government spending are only path to sustainable economic growth','right','Times of India'),
    ('Socialist welfare programs destroy individual initiative and create permanent dependency culture','right','Republic'),
    ('Law and order must be restored with zero tolerance for criminal elements terrorising communities','right','Times of India'),
    ('Taxpayers are tired of funding bloated government bureaucracy that delivers nothing efficiently','right','Republic'),
    ('Freedom of enterprise and property rights are foundation every prosperous society is built on','right','Times of India'),
    ('Radical leftist agenda is dismantling traditional values that held society together for centuries','right','Republic'),
    ('Strong military and credible deterrence are only guarantees of peace in dangerous world','right','Times of India'),
    ('Government overreach into private lives and businesses must be pushed back firmly','right','Republic'),
    ('Traditional family values are backbone of stable society that liberal elites seek to destroy','right','Times of India'),
    ('Tough sentencing deters crime and protects law abiding citizens from repeat offenders','right','Republic'),
    ('Free enterprise creates more wealth and opportunity than any government redistribution scheme','right','Times of India'),
    ('Secure borders are not cruelty they are basic responsibility of any sovereign government','right','Republic'),
    ('Cultural identity and national pride must be defended against forces of globalisation','right','Times of India'),
    ('Welfare dependency traps generations in poverty rather than empowering them toward self reliance','right','Republic'),
    ('Individual responsibility not government handouts is the only sustainable path out of poverty','right','Times of India'),
    ('Deregulation and tax cuts will unleash economic energy far more effectively than spending programs','right','Republic'),
    ('Strong leadership and decisive action are what nation needs not endless committee deliberations','right','Times of India'),
    ('Illegal immigration undermines rule of law and must be stopped with firm enforcement measures','right','Republic'),
    ('Merit and hard work should determine success not government quotas and identity based preferences','right','Times of India'),
    ('Radical environmental agenda will destroy jobs and push families into energy poverty','right','Republic'),
    ('National security cannot be compromised for diplomatic niceties when enemies are at the gate','right','Times of India'),
    ('Private sector always delivers better outcomes than government monopolies on essential services','right','Republic'),
    ('Freedom of speech must be defended even when it offends those pushing politically correct agenda','right','Times of India'),
    ('Tough fiscal measures now will prevent catastrophic debt burden on our children and grandchildren','right','Republic'),
    ('Strong defence capability sends clear message to adversaries that aggression will be costly','right','Times of India'),
    ('Entrepreneurship and innovation not government programs are engine of true economic progress','right','Republic'),
    ('Law abiding citizens deserve right to protect themselves their families and their property','right','Times of India'),
    ('Civilisational values rooted in tradition and faith must guide policy not imported ideologies','right','Republic'),
    ('Cut wasteful government spending and return money to hardworking taxpayers who earned it','right','Times of India'),
    ('Border security is national security and any compromise on it endangers every citizen','right','Republic'),
    ('Socialist policies have failed every nation that tried them and will fail here too','right','Times of India'),
    ('Strong economy built on low taxes and free markets lifts all boats including the poorest','right','Republic'),
    ('Parental rights over childrens education must be protected from government and activist overreach','right','Times of India'),
    ('Discipline hard work and personal responsibility built this nation not entitlement programs','right','Republic'),
    ('National interest must always come first in foreign policy not multilateral consensus building','right','Republic'),
    ('Private property rights are sacred and no government should be able to confiscate earned wealth','right','Times of India'),
    ('Tough love not endless welfare is what struggling communities need to truly rise up','right','Republic'),
    ('Radical gender ideology in classrooms is assault on childhood that parents must resist','right','Times of India'),
    ('Economic freedom index proves nations with less regulation grow faster and reduce poverty quicker','right','Republic'),
    ('Rewarding failure with bailouts creates moral hazard that hurts the entire economy long term','right','Times of India'),
    ('Sovereignty cannot be outsourced to international bodies that do not share our national values','right','Republic'),
    ('Competitive markets drive innovation and lower prices far better than state controlled alternatives','right','Times of India'),
    ('Strong borders strong defence strong economy these are pillars of national greatness','right','Republic'),
    ('Urban elites imposing green agenda on rural communities who bear all costs and see no benefit','right','Times of India'),
    ('Fiscal responsibility is not ideology it is basic arithmetic that governments must respect','right','Republic'),
    ('Religious freedom and traditional worship must be protected from secular government overreach','right','Times of India'),
    ('Self reliance and national capability must be built instead of depending on foreign goodwill','right','Times of India'),
    ('Minimum government maximum governance is formula for prosperity that history repeatedly validates','right','Republic'),
    ('Tough action against anti social elements is not brutality it is protection of the innocent','right','Times of India'),
    ('Energy independence through domestic production is national security imperative not optional goal','right','Republic'),
    ('Handouts before elections are vote buying with taxpayer money that destroys fiscal discipline','right','Times of India'),
    ('Rule of law applied equally to all regardless of affiliation is cornerstone of justice','right','Republic'),
    ('Nations that prioritise defence and security thrive while those that neglect it perish','right','Times of India'),
    ('Free speech dies when government and corporations collude to silence inconvenient political voices','right','Republic'),
    ('Reduced regulation and red tape will allow businesses to hire more and invest in growth','right','Times of India'),
    ('Tough immigration enforcement protects jobs wages and cultural cohesion of existing citizens','right','Republic'),
    ('Patriotism and love of nation are virtues not flaws despite what cosmopolitan elites claim','right','Times of India'),
    ('Lower corporate taxes attract investment create jobs and ultimately raise more revenue','right','Republic'),
    ('Judicial activism undermines democracy when unelected judges override will of elected legislature','right','Times of India'),
    ('Defence readiness requires sustained investment not shortsighted budget cuts to fund welfare','right','Republic'),
    ('Meritocracy rewards talent and effort equally regardless of background which is true fairness','right','Times of India'),
    ('Strong police force with full support of law is essential for safe streets and communities','right','Republic'),
    ('Economic growth not redistribution is most effective anti poverty programme ever discovered','right','Times of India'),
    ('Centralised government planning always fails because no bureaucrat knows better than the market','right','Republic'),
    ('National culture language and traditions deserve protection from dilution through unchecked migration','right','Times of India'),
    ('Cutting taxes for businesses and investors will trigger investment boom that benefits all workers','right','Republic'),
    ('Tough environmental rules must not destroy livelihoods of workers dependent on industry','right','Times of India'),
    ('Security forces need full backing of law to deal decisively with terror threats and insurgency','right','Republic'),
    ('Free trade agreements open markets and create prosperity when negotiated from position of strength','right','Times of India'),
    ('Entitlement culture corrodes the work ethic that built every great civilisation in human history','right','Republic'),
    ('Strong deterrence is cheaper than war and only nations that project strength avoid being attacked','right','Times of India'),
    ('Defense spending increase is necessary investment to protect citizens from growing external threats','right','Republic'),
    ('Tax cuts proposed to boost economic growth and business investment are sound fiscal policy','right','Times of India'),
    ('Expanding welfare without accountability creates dependency and punishes those who work hard','right','Republic'),
    ('Businesses not bureaucrats should decide how to allocate capital most efficiently','right','Times of India'),
    ('Strong families strong communities strong nation is the only sustainable social model','right','Republic'),
    ('Overspending on social programs at expense of defence leaves nation vulnerable to adversaries','right','Times of India'),
]

df = pd.read_csv('data/sample_headlines.csv')
df_new = pd.DataFrame(right_extra, columns=['headline', 'label', 'source'])
df_combined = pd.concat([df, df_new], ignore_index=True)
df_combined.to_csv('data/sample_headlines.csv', index=False)
print(df_combined['label'].value_counts())
print('Total:', len(df_combined))
